### ISSUE TITLE
Integration does not identify cancelled trips

### ISSUE THREAD

**Issue by rgerbranda** [bollewolle/pydelijn#14]
The realtime info of a cancelled bus is "GESCHRAPT"

In api.py, line 132 I should add the following code:

```
                        elif realtime_info[0] == "GESCHRAPT":
                            is_realtime = False
                            final_destination = "<del>" + final_destination + "</del> <b>geschrapt</b>";
```

My considerations:
- is html allowed in the code?
- is the integration multilingual?

**Comment by Emilv2** [comment]
Why would you want to put html in the code? The api is in Dutch, but I'll keep the code in English, multilingual should be done in the frontend.

**Comment by rgerbranda** [comment]
I put some html in the code to directly have the lovelace card formatted a bit.
But I can imagine you create a new value indicating that the trip is cancelled an that the lovelace card does the formating.

![2021-12-31 12_06_51-Overzicht - Home Assistant](https://user-images.githubusercontent.com/11868439/147820091-c6c675d2-81e7-49a0-893c-e062187b6102.png)

**Comment by sebadv** [comment]
In the same theme I also have seen this with "GEENREALTIME"

Logger: pydelijn.common
Source: /usr/local/lib/python3.9/site-packages/pydelijn/api.py:137
First occurred: 10:55:25 AM (40 occurrences)
Last logged: 11:28:56 AM

unknown realtime info: ['GESCHRAPT', 'GEENREALTIME']

**Comment by Emilv2** [comment]
Do you know if this information is documented somewhere?

**Comment by rgerbranda** [comment]
What I can find is: https://data.delijn.be/docs/services/KernOpenDataServicesV1/operations/geefDoorkomstenVoorHalte?

"predictionStatussen" is an array. The first element will be "GESCHRAPT" when a bus is cancelled.

**Comment by Emilv2** [comment]
Added in pydelijn release 1.1.0. (HomeAssistant and the lovelace card still need to be updated.)

**Comment by rgerbranda** [comment]
Thanks! For the time being I updated the package in Home Assistant and testing the output.

**Comment by rgerbranda** [comment]
Hi @Emilv2 what is the procedure to get this release in Home Assistant?
