### ISSUE TITLE
De Lijn is closing the beta version

### ISSUE THREAD

**Issue by rgerbranda** [bollewolle/pydelijn#15]
Today I received a message from De Lijn regarding their systems. The ```BASE_URL``` in common.py refers to the beta environment.

_Dear subscriber of the De Lijn Open Data Platform,
 
We’re currently upgrading the backend systems of our “Open Data”.
As a result we’ll be removing the “beta” version by the end of august  2023. Please upgrade your application to the “v1” version if needed.
 
Kind regards,                                                                 De Lijn_

**Comment by bollewolle** [comment]
I received the mail as well, but it's best you create a new issue at this repo: https://github.com/Emilv2/pydelijn

I'm no longer maintaining the pydelijn PyPi package, the master repo is in fact @Emilv2's. I do see that on PyPi it does still link to this one, so I guess that repo's setup.py needs some updating. But it's that repo that contains the latest version 1.0.0 compared to mine that is still stuck at 0.6.1.

Apologies for the confusion.

**Comment by rgerbranda** [comment]
Hi, @Emilv2 has disabled issues. It looks like the package is not maintained anymore. By that I suggest to remove the 'De Lijn' integration from Home Assistant.

**Comment by Emilv2** [comment]
I don't remember disabling issues. I don't really use this plugin anymore and don't have much time to work on it. If it's just changing the URL that I can do.

**Comment by rgerbranda** [comment]
I don't use the package anymore because it lacks important information: is a bus driving or not.
https://github.com/bollewolle/pydelijn/issues/14

Another issue seems to be that PyPi is not up to date. Which package is used by Home Assistant?

As alternative I use https://www.delijn.be/realtime/105606/8 in an iframe in Home Assistant

**Comment by Emilv2** [comment]
Ok, It seems like the API itself hasn't changed, expect an update before the api is closed. I have opened issues.

**Comment by Emilv2** [comment]
Fixed in pydelijn 1.1.0
